name: Enhancement
description: Have an idea for DESrv? Describe it in issue!
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting something new to DESrv! But please read [contribution guidelines](https://github.com/Blusutils/DESrv/blob/master/CONTRIBUTING.md#3-enhancements) before you start.
  - type: textarea
    id: enhancement
    attributes:
      label: Enhancement describation
      description: Please provide a clear and complete description of your idea.
    validations:
      required: true
  - type: checkboxes
    id: agreed
    attributes:
      label: Agreements
      options:
        - label: I have read [contribution guidelines](https://github.com/Blusutils/DESrv/blob/master/CONTRIBUTING.md#3-enhancements) for enhancements.
          required: true
