# Artifacts on intermediate per-commit DESrv build
name: Build DESrv Artifacts

on:
  # trigger it only on push
  push:
    paths:
      # track C#, .NET and VS files
      - "**.cs"
      - "**.csproj"
      - "**.sln"
    # only when pushing to theese branches
    branches:
      - "desrv2.0"
      - "master"
      - "main"

jobs:

  buildwin:
    # yes, it's genius to make a build for Windows on Windows
    runs-on: windows-latest
    steps:
    # just clone DESrv repo
    - name: Clone repository
      uses: actions/checkout@v3
    # setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    # restore nuget
    - name: Restore dependencies
      run: dotnet restore DESrv.sln --nologo
    # run tests
    - name: Run tests
      run: dotnet test DESrv.sln
    # do build!
    - name: Build
      run: dotnet build -c Debug -o outs-win --sc -v n --nologo
      working-directory: DESrv/
    # upload build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: DESrv-Windows-Debug
        # A file, directory or wildcard pattern that describes what to upload
        path: DESrv/outs-win

  buildlinux:
    runs-on: ubuntu-latest
    steps:
    # just clone DESrv repo
    - name: Clone repository
      uses: actions/checkout@v3
    # setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    # restore nuget
    - name: Restore dependencies
      run: dotnet restore DESrv.sln --nologo
    # run tests
    - name: Run tests
      run: dotnet test DESrv.sln
    # do build!
    - name: Build
      run: dotnet build -c Debug -o outs-linux --sc -v n --nologo
      working-directory: DESrv/
    # upload build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: DESrv-Linux-Debug
        path: DESrv/outs-linux